# OpenAI API Key
OPENAI_API_KEY = "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" 